"""Add age field

Revision ID: dcb489bad5c8
Revises: 6fdd043a72e1
Create Date: 2026-09-03 10:49:01.369339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcb489bad5c8'
down_revision: Union[str, Sequence[str], None] = '6fdd043a72e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('persons', sa.Column('age', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('persons', 'age')
    # ### end Alembic commands ###
